[build]
  publish = "public"         
  functions = "functions"    

[dev]
  
  environment = { COHERE_API_KEY = "wRvOaNnpamvr7jD8ho9Ah8j8Ngn3USPwPltFJgs5" }
  framework = "#custom"   
  command = "npm run dev" 
  targetPort = 5000       
  port = 8888             

 [[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200